ecommerce/accounts/urls.py
from django.urls import path


from .views import (UserLoginView, UserRegistrerView,
                    UserLogoutView)


app_name = 'accounts'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrerView.as_view(), name='register'),
   
]

ecommerce/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    # path('', views.chat_view, name='chat'),
]

ecommerce/products/urls.py
from django.urls import path
from . views import Home
from cart.views import add_to_cart, remove_from_cart, CartView
app_name= 'mainapp'

urlpatterns = [
    path('', Home.as_view(), name='home'),
     path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
]

ecommerce/products/models.py
from django.db import models
from django.db.models.signals import pre_save

from .utils import unique_slug_generator


# /***************************************************************************************
# *    Title: <MANASCODE>
# *    Author: <Manas Paul>
# *    Date: <21 August 2019>
# *    Code version: <python>
# *    Availability: <https://manascode.com/django-ecommerce-website-tutorial-part-one/>
# *   Edited by: Ablehulu Debebe
# ***************************************************************************************/

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=300)
    primaryCategory = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class  Product(models.Model):
    mainimage = models.ImageField(upload_to='products/',null=True ,blank=True)
    name = models.CharField(max_length=300)
    slug = models.SlugField(null=True,blank=True)
    categories = models.ManyToManyField(Category)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = models.PositiveIntegerField()


    def __str__(self):
        return self.name

def get_product_slug(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(get_product_slug,sender=Product)

ecommerce/products/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


from django.views.generic import ListView
from products.models import Product


class Home(ListView):
    model = Product
    fileds = '__all__'
    template_name = 'products/home.html'


def chat(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse('index'))
    else:
        title = "Chat Room"
        username = request.POST.get('username')
        return render(request,'chat.html',{"title":title,"username":username})



ecommerce/templates/products/snippets/css.html
 {% load static %}
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">

ecommerce/templates/products/snippets/js.html
{% load static %}

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<script src="{% static 'js/chat.js' %}" crossorigin="anonymous"></script>

ecommerce/templates/products/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="#"><i class="fa fa-shopping-cart"></i> Debebe Ecommerce Site</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mainapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:cart-home' %}">Carts</a>
      </li>
      {% if request.user.is_authenticated %}
         <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>

      {% else %}

       <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
      {% endif %}
      </ul>
    
  </div>
</nav>